### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by maxsiz** [platinum-engineering/insulin-calc#1]
Stefan, [04.08.21 20:10]
I finally got around reviewing the contract. Sorry for the delay. Here are my findings.

Stefan, [04.08.21 20:10]

- [x] 1. It would be nice if the contract would include a few hard-coded well-known Insulins, and allow for the user to add/remove other Insulins to the lookup table.
_No problem,  please send  me for table for hard coding.   But If you will use event-based smart contract as storage it is not useful I think._

Stefan, [04.08.21 20:11]

- [ ] 2. We will want to store the Insulin duration in seconds. It would be awesome if the contract could somehow make this clear with a custom data type maybe.
_Only native data types available when you reading events from storage.  So  seconds - it is just uint.._

Stefan, [04.08.21 20:12]

- [x] 3. Can we rename the following please?
Stefan, [04.08.21 20:13]
bloodGlucose -> glucose
carbohydrateIntake -> carbs
unitsOfInsulin -> units
__No  problem__

Stefan, [04.08.21 20:13]

- [ ] 4. We will want to store the glucose value in mg/dL and it would be awesome if the contract could somehow make this clear with a custom data type maybe.
_same as 2_

Stefan, [04.08.21 20:13]

- [x] 5. Can we rename writeMeasure() to bolus() please. Because when you give yourself insulin, this is referred to as a “bolus”.
_Yes,  ok_
Stefan, [04.08.21 20:14]

- [ ] 6. I love how few gas this contract consumes, but I am unsure if the event-driven approach allows for easy queries of archive data. We do need that eventually.

**Comment by maxsiz** [comment]
@svanas Could you please send me insulin names for hardcode?

> It would be nice if the contract would include a few hard-coded well-known Insulins, and allow for the user to add/remove other Insulins to the lookup table.

**Comment by svanas** [comment]
> Could you please send me insulin names for hardcode?

1. Novorapid (duration: 180 minutes)
2. Humuline (duration: 300 minutes)
